### ISSUE TITLE
Add releases and versioning

### ISSUE THREAD

**Issue by mikkonie** [bihealth/davrods-docker#5]
Similar to [irods-docker](https://github.com/bihealth/irods-docker), we should introduce clearly versioned releases for the image.

We should also stop building a `latest` version of the image, as users of this image should, similar to `irods-docker`, pin down a specific version to ensure compatibility.

## Tasks

- [x] Tag current main branch as legacy v4.2 release
- [x] Add milestone for v4.3 release
- [x] Add changelog
- [x] Add build version to version number (see docker-irods)
- [x] Stop building `latest` version of the image

**Comment by mikkonie** [comment]
Done.
